micronaut:
  application:
    name: pixKeyManagerGrpc

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/pix-grpc`}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USER:alex}
    password: ${DB_PASSWORD:alex}
    dialect: ${DB_DIALECT:POSTGRES}
    schema-generate: UPDATE

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
        format_sql: false

values:
  erp-itau:
    host: ${ERP_ITAU_HOST:localhost}
    port: ${ERP_ITAU_PORT:9091}
  bcb:
    host: ${BCB_HOST:localhost}
    port: ${BCB_PORT:8082}